### ISSUE TITLE
SEO - Search Engine Optimization

### ISSUE THREAD

**Issue by t3nGri** [acikkaynak/afet-org#12]
İnsanların oluşturduğumuz datalara/sonuçlara Google'dan veya Arama motorlarından hızlıca ulaşabilmesi için SEO - Arama motoru optimizasyonu yapılması gerekiyor. Çalıştığım SEO şirketimle görüştüm tümüyle bu konuda destek vermeye hazırız.
Şirketim: holisticseo.digital

**Comment by sustartx** [comment]
Tamamlandı.
