### ISSUE TITLE
Create date eklenmesi

### ISSUE THREAD

**Issue by sahin52** [acikkaynak/afet-org#13]
Eklenen verilerin eklenme tarihinin konulması son haberlerin alınabilmesi için etkili olabilir

**Comment by ramazansancar** [comment]
Kontrol sağladığımda tarih bilgisinin yer aldığını gördüm. Eğer halen sorun olduğunu düşünüyorsanız yazabilirsiniz.

Bkz.
![image](https://user-images.githubusercontent.com/8878055/217800213-99c59307-268b-48f4-8288-1bc1e290e0cb.png)
