### ISSUE TITLE
Bazı eksik meta etiketler.

### ISSUE THREAD

**Issue by t3nGri** [acikkaynak/afet-org#14]
- Sosyal Medyada paylaşılan linklerde, web sitesinin amacını daha iyi açıklamak için görsel ve twitter card ve open graph kodu

- Web site icon görseli ve html kodu

```
<link rel="icon" href="https://depremyardim.com/depremyardim.png">

<meta property="og:type" content="website">
<meta property="og:url" content="https://depremyardim.com" >
<meta property="og:title" content="Deprem Yardım Çağrısı ve Arama Kurtarma">
<meta property="og:description" content="Depremde göçük altında kalan insanların ve yakınlarının yardım çağrıları toplanıyor.">
<meta property="og:image" content="https://depremyardim.com/depremyardimcagri.png" >

<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Deprem Yardım Çağrısı ve Arama Kurtarma">
<meta name="twitter:description" content="Depremde göçük altında kalan insanların ve yakınlarının yardım çağrıları toplanıyor.">
<meta name="twitter:image" content="https://depremyardim.com/depremyardimcagri.png">
```

sosyal medya görseli:
![depremyardimcagri](https://user-images.githubusercontent.com/76410812/217384212-d16cc760-9e17-4f70-8e65-a93c43188652.png)

web site icon görseli:
![depremyardim](https://user-images.githubusercontent.com/76410812/217384284-622021ae-4ff5-4f98-881b-46f397ada1fd.png)

**Comment by omeraydmr** [comment]
Bunu yapabilirim sanırım ama projeyi klonlamam rağmen dosya erişimim yok

**Comment by t3nGri** [comment]
ilgili kişilere iletebilecek misin?

**Comment by sustartx** [comment]
Tamamlandı.

**Comment by ramazansancar** [comment]
Kontrol sağladığımda eklendiğini gördüm. Öneriniz için teşekkürler.

Bkz.
![image](https://user-images.githubusercontent.com/8878055/217801899-fa23a4fa-e773-4d74-be6d-d34935b570e2.png)
