### ISSUE TITLE
depremyardim.com domain üzerinde http -> https yönlendirmesi yapılması gerekiyor

### ISSUE THREAD

**Issue by omeruluoglu** [acikkaynak/afet-org#7]
**HTTP olarak girildiğinde il seçim gelmemekte ve zorunlu alan olduğu için veri girişi sağlanamıyor**

<img width="1001" alt="Screen Shot 2023-02-07 at 12 18 43" src="https://user-images.githubusercontent.com/14353028/217204561-f7be70c6-04d9-4ac0-93f8-3cb67ec6ff39.png">
<img width="1179" alt="Screen Shot 2023-02-07 at 12 18 57" src="https://user-images.githubusercontent.com/14353028/217204568-f1c74449-3c92-4872-b3ac-24579e473d2c.png">

**Comment by ramazansancar** [comment]
İlgili ekibe yönlendirme yapıyorum. Teşekkürler

**Comment by ramazansancar** [comment]
Kontrol sağladımda https 'ye yönlendirmesi sağlandığını gördüm. Şu an sorun yok gibi duruyor.

**Comment by omeruluoglu** [comment]
Evet yönlendirme yapıyor şu anda 👍
